module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "app-border": "var(--app-border)",
        "app-primary": "var(--app-primary)",
        black: "var(--black)",
        "color-dark-yellow": "var(--color-dark-yellow)",
        "color-light-green": "var(--color-light-green)",
        dark: "var(--dark)",
        "dark-100": "var(--dark-100)",
        "dark-200": "var(--dark-200)",
        "dark-300": "var(--dark-300)",
        "dark-400": "var(--dark-400)",
        "dark-50": "var(--dark-50)",
        "dark-500": "var(--dark-500)",
        "dark-600": "var(--dark-600)",
        "dark-700": "var(--dark-700)",
        "dark-900": "var(--dark-900)",
        "dark-950": "var(--dark-950)",
        "gray-4": "var(--gray-4)",
        "gray-50": "var(--gray-50)",
        "label-dark-primary": "var(--label-dark-primary)",
        "label-dark-tertiary": "var(--label-dark-tertiary)",
        "label-light-primary": "var(--label-light-primary)",
        light: "var(--light)",
        "main-blackblack-500": "var(--main-blackblack-500)",
        "primary-50": "var(--primary-50)",
        "primary-600": "var(--primary-600)",
        "primary-900": "var(--primary-900)",
        "secondary-50": "var(--secondary-50)",
        "secondarylglight-grey-400": "var(--secondarylglight-grey-400)",
        tertiary: "var(--tertiary)",
        white: "var(--white)",
        "white-900": "var(--white-900)",
        "white-950": "var(--white-950)",
        "whitewhite-100": "var(--whitewhite-100)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-normal": "var(--body-normal-font-family)",
        "body-small": "var(--body-small-font-family)",
        h4: "var(--h4-font-family)",
        h6: "var(--h6-font-family)",
        "link-normal": "var(--link-normal-font-family)",
        "link-small": "var(--link-small-font-family)",
        "link-xsmall": "var(--link-xsmall-font-family)",
        "typography-body1-bold": "var(--typography-body1-bold-font-family)",
        "typography-body2-bold": "var(--typography-body2-bold-font-family)",
        "typography-body2-medium": "var(--typography-body2-medium-font-family)",
        "typography-body2-regular":
          "var(--typography-body2-regular-font-family)",
        "typography-body3-medium": "var(--typography-body3-medium-font-family)",
        "typography-body3-regular":
          "var(--typography-body3-regular-font-family)",
        "typography-body4-bold": "var(--typography-body4-bold-font-family)",
        "typography-body4-regular":
          "var(--typography-body4-regular-font-family)",
        "typography-display-xl-extra-bold":
          "var(--typography-display-xl-extra-bold-font-family)",
        "typography-h2-extra-bold":
          "var(--typography-h2-extra-bold-font-family)",
        "typography-h3-bold": "var(--typography-h3-bold-font-family)",
        "typography-h5-bold": "var(--typography-h5-bold-font-family)",
        "typography-h5-medium": "var(--typography-h5-medium-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
